name: Leo
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Display dotnet info
        run: dotnet --info
      - name: Leo.Data.Domain.Tests
        run: dotnet test test/Leo.Data.Domain.Tests/ -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      - name: Leo.Web.Api.Tests
        run: dotnet test test/Leo.Web.Api.Tests/ -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
